name: Build and Publish Package  
  
on:  
  push:  
    branches:  
      - feature/import-wxreader  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v3  
  
    - name: Set up Node.js  
      uses: actions/setup-node@v3  
      with:  
        node-version: '18'  
  
    - name: Configure npm  
      run: |  
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc  
      env:  
        NPM_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}  
  
    - name: Install dependencies  
      run: npm install  
  
    - name: Build the package  
      run: npm run build --version_type=patch  
  
    - name: Publish package  
      run: npm publish